'use client'

import Image from 'next/image'
import { useEffect, useRef, useState } from 'react'
import { Armchair, ArrowLeft, ArrowRight, CalendarClock, Check, Coffee, Clock3, Menu, ParkingCircle, Scissors, Snowflake, Sparkles, Wifi, X } from 'lucide-react'
import { businessConfig, faq, formatBRL, gallery, portfolioByCategory, professionals, reviews, services, socialProof, waLink } from '@/lib/demo-data'

type Reference = (typeof gallery)[number]

type ModalContext = { service?: string; professional?: string; category?: string; reference?: Reference }

const servicePrice = (item: (typeof services)[number]) => item.priceMode === 'from' ? `a partir de ${formatBRL(item.price)}` : item.priceMode === 'consult' ? 'sob consulta' : formatBRL(item.price)

function BeforeAfterSlider({ before, after, alt }: { before: string; after: string; alt: string }) {
  const [position, setPosition] = useState(50)
  return <div className="before-after" style={{ '--split': `${position}%` } as React.CSSProperties}>
    <Image className="before-after-image" src={after} alt={`${alt} — depois`} fill sizes="(max-width: 900px) 100vw, 52vw" priority />
    <div className="after-layer"><Image className="before-after-image" src={before} alt={`${alt} — antes`} fill sizes="(max-width: 900px) 100vw, 52vw" /></div>
    <span className="compare-label compare-before">Antes</span><span className="compare-label compare-after">Depois</span><span className="compare-divider" aria-hidden="true"><span /></span>
    <label className="sr-only" htmlFor="before-after-range">Comparar antes e depois da coloração</label><input id="before-after-range" className="compare-range" type="range" min="0" max="100" value={position} onChange={(event) => setPosition(Number(event.target.value))} aria-valuetext={`${position}% da comparação entre antes e depois`} />
  </div>
}

function InterestModal({ context, onClose }: { context: ModalContext; onClose: () => void }) {
  const [step, setStep] = useState(context.service ? 2 : 1)
  const [service, setService] = useState(context.service || '')
  const [professional, setProfessional] = useState(context.professional || '')
  const [reference, setReference] = useState<Reference | undefined>(context.reference)
  const [preferredDate, setPreferredDate] = useState('')
  const [timeOfDay, setTimeOfDay] = useState('')
  const [observation, setObservation] = useState('')
  const dialogRef = useRef<HTMLDivElement>(null)
  const selected = services.find((item) => item.id === service)
  const chosenProfessional = professionals.find((item) => item.id === professional)
  const compatible = professionals.filter((item) => selected?.professionalIds.includes(item.id))
  const visibleServices = services.filter((item) => (!context.category || item.category === context.category) && (!context.professional || item.professionalIds.includes(context.professional)))
  const today = new Date().toISOString().slice(0, 10)

  useEffect(() => {
    dialogRef.current?.focus()
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onClose()
      if (event.key === 'Tab' && dialogRef.current) {
        const focusable = [...dialogRef.current.querySelectorAll<HTMLElement>('button, input')].filter((element) => !element.hasAttribute('disabled'))
        if (!focusable.length) return
        const first = focusable[0]
        const last = focusable[focusable.length - 1]
        if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus() }
        else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus() }
      }
    }
    document.addEventListener('keydown', onKeyDown)
    return () => document.removeEventListener('keydown', onKeyDown)
  }, [onClose])

  const selectService = (id: string) => {
    const next = services.find((item) => item.id === id)
    setService(id)
    if (professional && next && !next.professionalIds.includes(professional)) setProfessional('')
    if (reference && reference.relatedServiceId !== id) setReference(undefined)
    setStep(2)
  }
  const preference = preferredDate && timeOfDay ? `${preferredDate.split('-').reverse().join('/')} · ${timeOfDay}` : preferredDate ? `${preferredDate.split('-').reverse().join('/')} · faixa do dia a combinar` : timeOfDay ? `Data a combinar · ${timeOfDay}` : 'A combinar'
  const referenceTitle = reference?.title.trim()
  const includesReference = Boolean(referenceTitle && referenceTitle !== selected?.name?.trim())
  const message = `Olá! Gostaria de solicitar um horário.\nServiço: ${selected?.name || 'A combinar'}\nProfissional: ${chosenProfessional?.name || 'Sem preferência'}\nPreferência: ${preference}${observation ? `\nObservação: ${observation}` : ''}${includesReference ? `\nReferência: ${referenceTitle}` : ''}\nVocês podem confirmar a disponibilidade?`

  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div ref={dialogRef} className="booking-modal booking-flow" role="dialog" aria-modal="true" aria-labelledby="interest-title" tabIndex={-1}><button className="icon-button modal-close" aria-label="Fechar" onClick={onClose}><X /></button><p className="eyebrow">Aura Essencial</p><h2 id="interest-title">Solicite seu horário</h2><div className="booking-steps" aria-label="Etapas da solicitação">{['Serviço', 'Profissional', 'Preferências', 'Resumo'].map((label, index) => <span className={step === index + 1 ? 'active' : step > index + 1 ? 'done' : ''} key={label}>{step > index + 1 ? <Check size={12} /> : index + 1} {label}</span>)}</div>
    {step === 1 && <><p className="modal-description">Escolha o serviço que você gostaria de consultar.</p><div className="choice-list">{visibleServices.map((item) => <button type="button" className="choice" key={item.id} onClick={() => selectService(item.id)}><span><strong>{item.name}</strong><small>{item.category} · {item.duration} min</small></span><b>{servicePrice(item)}</b></button>)}</div></>}
    {step === 2 && selected && <><p className="service-category">{selected.category}</p><h3>{selected.name}</h3><p className="modal-description">{selected.description}</p>{reference && <div className="reference-preview"><Image src={reference.src} alt={reference.title} width={72} height={54} /><span>Inspiração relacionada a <strong>{selected.name}</strong>.</span></div>}<div className="service-meta"><span><Clock3 size={13} />{selected.duration} min</span><span>{servicePrice(selected)}</span></div>{selected.includes && <p className="service-extra"><strong>Inclui</strong>{selected.includes}</p>}{selected.note && <p className="service-extra"><strong>Observação</strong>{selected.note}</p>}<p className="eyebrow preference-label">Profissional (opcional)</p><div className="choice-list"><button type="button" className={!professional ? 'choice selected' : 'choice'} onClick={() => setProfessional('')}><span><strong>Sem preferência</strong><small>Deixe a equipe indicar</small></span></button>{compatible.map((person) => <button type="button" className={professional === person.id ? 'choice selected' : 'choice'} key={person.id} onClick={() => setProfessional(person.id)}><span><strong>{person.name}</strong><small>{person.role}</small></span></button>)}</div><div className="modal-actions"><button type="button" className="text-link" onClick={() => setStep(1)}><ArrowLeft size={14} /> Voltar</button><button type="button" className="button button-primary" onClick={() => setStep(3)}>Continuar <ArrowRight size={16} /></button></div></>}
    {step === 3 && <><p className="modal-description">Informe uma preferência, se quiser. O salão confirma a disponibilidade pelo WhatsApp.</p><div className="form-grid"><label>Data preferida (opcional)<input type="date" min={today} value={preferredDate} onChange={(event) => setPreferredDate(event.target.value)} /></label><fieldset className="time-of-day-field"><legend>FAIXA DO DIA (OPCIONAL)</legend><div className="time-of-day-grid">{['Manhã', 'Início da tarde', 'Fim da tarde', 'Início da noite'].map((option) => <button type="button" className={timeOfDay === option ? 'time-of-day-option selected' : 'time-of-day-option'} key={option} aria-pressed={timeOfDay === option} onClick={() => setTimeOfDay(timeOfDay === option ? '' : option)}>{option}</button>)}</div></fieldset></div><label className="observation-field">Observação (opcional)<textarea maxLength={160} placeholder="Ex.: quero manter o comprimento." value={observation} onChange={(event) => setObservation(event.target.value)} /></label><div className="modal-actions"><button type="button" className="text-link" onClick={() => setStep(2)}><ArrowLeft size={14} /> Voltar</button><button type="button" className="button button-primary" onClick={() => setStep(4)}>Revisar <ArrowRight size={16} /></button></div></>}
    {step === 4 && <><div className="summary-list"><p><span>Serviço</span><strong>{selected?.name || 'A combinar'}</strong></p><p><span>Profissional</span><strong>{chosenProfessional?.name || 'Sem preferência'}</strong></p><p><span>Data preferida</span><strong>{preferredDate ? preferredDate.split('-').reverse().join('/') : 'A combinar'}</strong></p>{timeOfDay && <p><span>Faixa do dia</span><strong>{timeOfDay}</strong></p>}{reference && <p><span>Inspiração escolhida</span><strong>{reference.title}</strong></p>}{observation && <p><span>Observação</span><strong>{observation}</strong></p>}</div><p className="demo-message"><Sparkles size={15} />Esta é uma solicitação. O horário será confirmado pelo salão no WhatsApp.</p><div className="modal-actions"><button type="button" className="text-link" onClick={() => setStep(3)}><ArrowLeft size={14} /> Editar</button><a className="button button-primary whatsapp-cta" href={waLink(businessConfig.whatsapp, message)} target="_blank" rel="noreferrer">Enviar solicitação pelo WhatsApp <ArrowRight size={16} /></a></div></>}
  </div></div>
}

export default function Page() {
  const [category, setCategory] = useState('Todos'); const [serviceCategory, setServiceCategory] = useState('Todos'); const [mobileMenuOpen, setMobileMenuOpen] = useState(false); const [reference, setReference] = useState<Reference | null>(null); const [modalContext, setModalContext] = useState<ModalContext | null>(null); const [heroVisible, setHeroVisible] = useState(true); const [finalCtaVisible, setFinalCtaVisible] = useState(false); const heroRef = useRef<HTMLElement>(null); const finalCtaRef = useRef<HTMLElement>(null)
  useEffect(() => { const observer = new IntersectionObserver(([entry]) => setHeroVisible(entry.isIntersecting), { threshold: 0.15 }); if (heroRef.current) observer.observe(heroRef.current); return () => observer.disconnect() }, [])
  useEffect(() => { const observer = new IntersectionObserver(([entry]) => setFinalCtaVisible(entry.isIntersecting), { threshold: 0.15 }); if (finalCtaRef.current) observer.observe(finalCtaRef.current); return () => observer.disconnect() }, [])
  const filtered = category === 'Todos' ? gallery : portfolioByCategory[category as keyof typeof portfolioByCategory]
  const visibleServices = serviceCategory === 'Todos' ? services : services.filter((item) => item.category === serviceCategory)
  const openRequest = (context: ModalContext = {}) => { setReference(null); setModalContext(context) }
  return <main><header className="site-header"><a className="brand" href="#inicio"><span className="brand-mark">A</span><span>AURA ESSENCIAL</span></a><nav><a href="#servicos">Serviços</a><a href="#resultados">Resultados</a><a href="#studio">O studio</a><a href="#contato">Contato</a></nav><button className="button button-primary header-request" onClick={() => openRequest()}>Solicitar horário <ArrowRight size={16} /></button><button className="icon-button mobile-menu" aria-label="Abrir menu" aria-expanded={mobileMenuOpen} onClick={() => setMobileMenuOpen((open) => !open)}><Menu /></button>{mobileMenuOpen && <div className="mobile-nav"><a href="#servicos" onClick={() => setMobileMenuOpen(false)}>Serviços</a><a href="#resultados" onClick={() => setMobileMenuOpen(false)}>Resultados</a><a href="#studio" onClick={() => setMobileMenuOpen(false)}>O studio</a><a href="#contato" onClick={() => setMobileMenuOpen(false)}>Contato</a></div>}</header>
  <section className="hero" id="inicio" ref={heroRef}><div className="hero-copy"><p className="eyebrow">Beauty studio · Vila Madalena</p><h1>Beleza para viver do <em>seu jeito.</em></h1><p className="hero-text">Cabelos, unhas, maquiagem e olhar na Vila Madalena. Veja referências, consulte valores e solicite seu horário pelo WhatsApp.</p><div className="hero-actions"><button className="button button-primary" onClick={() => openRequest()}>Solicitar horário <ArrowRight size={17} /></button><a className="text-link" href="#servicos">Ver serviços <ArrowRight size={16} /></a></div><div className="hero-note"><span><strong>Atendimento com calma</strong> e atenção aos detalhes <Sparkles size={13} /></span><small className="hero-hours">Ter–Sáb · 9h–20h · Atendimento com hora marcada</small><small className="hero-rating">Como suas avaliações podem aparecer</small></div></div><div className="hero-image"><Image src="https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1400&q=85" alt="Mulher sorrindo em um ambiente de beleza" fill priority sizes="(max-width: 900px) 100vw, 50vw" /></div></section><aside className="demo-context-notice" aria-label="Contexto da demonstração"><strong>Demonstração Aura Essencial</strong><span>Fotos, cores, serviços, avaliações, endereço e WhatsApp são personalizados para cada salão.</span></aside>
  <section className="section portfolio" id="portfolio"><div className="section-heading"><div><p className="eyebrow">Nosso olhar</p><h2>Detalhes que falam.</h2><p>Explore referências e veja o serviço relacionado.</p></div><div className="filter-row">{['Todos','Cabelos','Unhas','Make','Olhar'].map((item) => <button className={category === item ? 'filter active' : 'filter'} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div></div><div className="gallery-grid">{filtered.map((item) => <button className="gallery-item" key={item.id} type="button" onClick={() => setModalContext({ service: item.relatedServiceId, category: item.category, reference: item })}><Image src={item.src} alt={item.alt} fill sizes="(max-width: 700px) 50vw, 25vw" /><span className="gallery-service-hint">{services.find((service) => service.id === item.relatedServiceId)?.name ?? 'Ver serviços'} <ArrowRight size={13} /></span></button>)}</div></section>
  <section className="section" id="servicos"><div className="section-heading"><div><p className="eyebrow">O que fazemos</p><h2>Seu ritual, do seu jeito.</h2></div><p>Serviços pensados para realçar o que você já tem de mais bonito — com técnica, escuta e um toque de Aura.</p></div><div className="filter-row service-filters">{['Todos','Cabelos','Unhas','Make','Olhar'].map((item) => <button className={serviceCategory === item ? 'filter active' : 'filter'} key={item} onClick={() => setServiceCategory(item)}>{item}</button>)}</div><div className="service-grid">{visibleServices.map((item) => <article className="service-card" key={item.id}><div className="service-icon"><Scissors size={21} /></div><div><p className="service-category">{item.category}</p><h3>{item.name}</h3><p>{item.description}</p><div className="service-meta"><span><Clock3 size={13} />{item.duration} min</span><span>{servicePrice(item)}</span></div><button className="button button-primary" onClick={() => openRequest({ service: item.id })}>{item.ctaLabel} <ArrowRight size={16} /></button></div></article>)}</div></section>
  <section className="results-section" id="resultados"><div className="results-intro"><p className="eyebrow">Exemplo de resultado</p><h2>Antes e depois que mostram o trabalho.</h2><p className="results-lead">Um exemplo de transformação e o que as clientes falam depois — a prova que ajuda quem chega a decidir mais rápido.</p></div>
    <div className="primary-result"><div className="primary-visual"><BeforeAfterSlider before={socialProof.transformation.before} after={socialProof.transformation.after} alt={socialProof.transformation.alt} /></div><div className="primary-result-copy"><p className="result-category">{socialProof.transformation.category}</p><h3>{socialProof.transformation.title}</h3><p>{socialProof.transformation.description}</p><button type="button" className="button button-primary" onClick={() => setModalContext({ service: socialProof.transformation.serviceId })}>Quero um resultado assim <ArrowRight size={15} /></button></div></div>
    <div className="proof-block"><div className="rating-summary"><span className="stars">★★★★★</span><strong>Como suas avaliações podem aparecer</strong><small>Na versão personalizada, este espaço recebe avaliações reais dos clientes do salão.</small></div><div className="customer-reviews">{reviews.map((review) => <article className="review" key={review.name}><span className="stars">{'★'.repeat(review.rating)}</span><p>{review.quote}</p><div className="review-meta"><strong>Exemplo demonstrativo</strong><small>Conteúdo ilustrativo — na versão personalizada, este espaço recebe avaliações reais do salão.</small></div></article>)}</div></div>
    <div className="results-closing"><p>Gostou desse resultado?</p><button type="button" className="button button-primary" onClick={() => openRequest()}>Solicitar horário <ArrowRight size={15} /></button></div></section>
  <section className="studio-section" id="studio"><div className="studio-amenities" aria-label="Comodidades do Aura"><div className="studio-amenity"><Wifi size={18} /><span>Wi‑Fi livre</span></div><div className="studio-amenity"><ParkingCircle size={18} /><span>Estacionamento fácil</span></div><div className="studio-amenity"><Coffee size={18} /><span>Cafézinho enquanto espera</span></div><div className="studio-amenity"><Snowflake size={18} /><span>Ambiente climatizado</span></div><div className="studio-amenity"><CalendarClock size={18} /><span>Atendimento com horário marcado</span></div><div className="studio-amenity"><Armchair size={18} /><span>Espaço confortável e acolhedor</span></div></div><div className="studio-copy"><p className="eyebrow">Sobre o Aura</p><h2>Um respiro no meio da cidade.</h2><p>O Aura Essencial nasceu para ser um lugar onde você não precisa performar nada. Aqui, beleza é conversa, presença e um pouquinho de tempo só seu.</p><div className="quote"><Sparkles size={20} /><p>“Saí daqui lembrando que cuidar de mim também pode ser leve.”</p></div></div></section>
  <section className="section faq-section" id="duvidas"><div className="section-heading"><div><p className="eyebrow">Antes de vir</p><h2>Dúvidas rápidas.</h2></div><p>O essencial antes de solicitar seu horário.</p></div><div className="faq-list">{faq.map((item) => <details key={item.question}><summary>{item.question}<ArrowRight size={15} /></summary><p>{item.answer}</p></details>)}</div></section>
  <section className="cta-section" ref={finalCtaRef}><p className="eyebrow">Seu tempo é precioso</p><h2>Quer solicitar um horário?</h2><p>Escolha o serviço e informe suas preferências. A equipe confirma a disponibilidade pelo WhatsApp.</p><button className="button button-primary" onClick={() => openRequest()}>Solicitar horário <ArrowRight size={16} /></button></section>
  <footer id="contato"><div className="footer-brand"><a className="brand" href="#inicio"><span className="brand-mark">A</span><span>AURA ESSENCIAL</span></a><p>Beleza para viver do seu jeito.</p></div><div><p className="footer-label">Visite a gente</p><p>{businessConfig.address}</p><p>{businessConfig.hours}</p>{businessConfig.practicalInfo?.map((item) => <small className="practical-item" key={item}>{item}</small>)}{businessConfig.mapsUrl && <a href={businessConfig.mapsUrl} target="_blank" rel="noreferrer">Como chegar</a>}</div><div><p className="footer-label">Fale com a gente</p><a href={waLink(businessConfig.whatsapp, 'Olá! Gostaria de informações sobre os serviços do Aura Essencial.')} target="_blank" rel="noreferrer">WhatsApp</a>{businessConfig.instagram && <a href={businessConfig.instagram.startsWith('http') ? businessConfig.instagram : `https://instagram.com/${businessConfig.instagram.replace('@', '')}`} target="_blank" rel="noreferrer">Instagram</a>}</div><div className="footer-bottom"><span>© 2026 Aura Essencial</span><span>Feito com cuidado.</span></div></footer>{!heroVisible && !finalCtaVisible && !modalContext && <div className="mobile-sticky-cta"><button className="button button-primary" onClick={() => openRequest()}>Solicitar horário <ArrowRight size={16} /></button></div>}{modalContext && <InterestModal context={modalContext} onClose={() => setModalContext(null)} />}</main>
}
